import { Command } from 'commander';
import { writeFileSync, appendFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { printSuccess, printError, printHint } from '../ui/output.js';
import { handleError } from '../utils/errors.js';

// ─── Completion Data ──────────────────────────────────────────────────────

const TOP_LEVEL_COMMANDS = ['auth', 'agent', 'config', 'preset', 'completion'];

const SUBCOMMANDS: Record<string, string[]> = {
  agent: ['start', 'stop', 'status', 'list', 'update', 'speak', 'interrupt', 'history', 'turns', 'watch'],
  auth: ['login', 'logout', 'status'],
  config: ['init', 'set', 'get', 'show', 'path'],
  preset: ['list', 'use'],
  completion: ['bash', 'zsh', 'fish', 'install'],
};

const AGENT_START_FLAGS = [
  '--channel', '--preset', '--model', '--tts', '--asr',
  '--json', '--dry-run', '--profile',
];

const PRESET_NAMES = [
  'openai-gpt4o', 'openai-mini', 'anthropic-claude', 'gemini', 'realtime-openai',
];

// ─── Bash Completion Script ───────────────────────────────────────────────

function generateBashScript(): string {
  return `# convoai bash completion
# Generated by: convoai completion bash
_convoai_completions() {
    local cur prev words cword
    _init_completion || return

    local toplevel="${TOP_LEVEL_COMMANDS.join(' ')}"
    local agent_cmds="${SUBCOMMANDS.agent.join(' ')}"
    local auth_cmds="${SUBCOMMANDS.auth.join(' ')}"
    local config_cmds="${SUBCOMMANDS.config.join(' ')}"
    local preset_cmds="${SUBCOMMANDS.preset.join(' ')}"
    local completion_cmds="${SUBCOMMANDS.completion.join(' ')}"
    local agent_start_flags="${AGENT_START_FLAGS.join(' ')}"
    local preset_names="${PRESET_NAMES.join(' ')}"

    # Determine position: find the subcommand level
    local cmd=""
    local subcmd=""
    local i
    for (( i=1; i < cword; i++ )); do
        case "\${words[i]}" in
            agent|auth|config|preset|completion)
                cmd="\${words[i]}"
                ;;
            start|stop|status|list|update|speak|interrupt|history|turns|watch|login|logout|init|set|get|show|path|use|bash|zsh|fish|install)
                if [[ -n "$cmd" ]]; then
                    subcmd="\${words[i]}"
                fi
                ;;
        esac
    done

    # Complete flags for specific subcommands
    if [[ "$cur" == -* ]]; then
        if [[ "$cmd" == "agent" && "$subcmd" == "start" ]]; then
            COMPREPLY=( $(compgen -W "$agent_start_flags" -- "$cur") )
            return
        fi
    fi

    # Complete flag values
    if [[ -n "$prev" ]]; then
        case "$prev" in
            --preset)
                COMPREPLY=( $(compgen -W "$preset_names" -- "$cur") )
                return
                ;;
        esac
    fi

    # Complete subcommands
    if [[ -n "$cmd" && -z "$subcmd" ]]; then
        case "$cmd" in
            agent)
                COMPREPLY=( $(compgen -W "$agent_cmds" -- "$cur") )
                return
                ;;
            auth)
                COMPREPLY=( $(compgen -W "$auth_cmds" -- "$cur") )
                return
                ;;
            config)
                COMPREPLY=( $(compgen -W "$config_cmds" -- "$cur") )
                return
                ;;
            preset)
                COMPREPLY=( $(compgen -W "$preset_cmds" -- "$cur") )
                return
                ;;
            completion)
                COMPREPLY=( $(compgen -W "$completion_cmds" -- "$cur") )
                return
                ;;
        esac
    fi

    # Complete top-level commands
    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W "$toplevel" -- "$cur") )
        return
    fi
}

complete -F _convoai_completions convoai
`;
}

// ─── Zsh Completion Script ────────────────────────────────────────────────

function generateZshScript(): string {
  return `#compdef convoai
# convoai zsh completion
# Generated by: convoai completion zsh

_convoai() {
    local -a toplevel_commands
    toplevel_commands=(
        'auth:Manage authentication credentials'
        'agent:Manage ConvoAI agents'
        'config:Manage CLI configuration'
        'preset:Manage agent presets'
        'completion:Generate shell completion scripts'
    )

    local -a agent_commands
    agent_commands=(
        'start:Start a new ConvoAI agent'
        'stop:Stop a running agent'
        'status:Show agent status'
        'list:List running agents'
        'update:Update a running agent'
        'speak:Send text for the agent to speak'
        'interrupt:Interrupt the agent'
        'history:Show conversation history'
        'turns:Show conversation turns'
        'watch:Watch agent status in real time'
    )

    local -a auth_commands
    auth_commands=(
        'login:Authenticate with the Agora ConvoAI platform'
        'logout:Remove stored credentials'
        'status:Show current authentication status'
    )

    local -a config_commands
    config_commands=(
        'init:Initialize configuration'
        'set:Set a configuration value'
        'get:Get a configuration value'
        'show:Show full configuration'
        'path:Show config file path'
    )

    local -a preset_commands
    preset_commands=(
        'list:List available presets'
        'use:Use a preset configuration'
    )

    local -a completion_commands
    completion_commands=(
        'bash:Generate bash completion script'
        'zsh:Generate zsh completion script'
        'fish:Generate fish completion script'
        'install:Auto-detect shell and install completions'
    )

    local -a preset_names
    preset_names=(${PRESET_NAMES.map((n) => `'${n}'`).join(' ')})

    _arguments -C \\
        '(-v --version)'{-v,--version}'[Show version]' \\
        '(-h --help)'{-h,--help}'[Show help]' \\
        '1:command:->command' \\
        '*::arg:->args'

    case $state in
        command)
            _describe -t commands 'convoai command' toplevel_commands
            ;;
        args)
            case $words[1] in
                agent)
                    _arguments -C \\
                        '1:subcommand:->subcmd' \\
                        '*::arg:->subargs'
                    case $state in
                        subcmd)
                            _describe -t commands 'agent subcommand' agent_commands
                            ;;
                        subargs)
                            case $words[1] in
                                start)
                                    _arguments \\
                                        '(-c --channel)'{-c,--channel}'[RTC channel name]:channel name' \\
                                        '--preset[Use a built-in preset]:preset name:(${PRESET_NAMES.join(' ')})' \\
                                        '--model[LLM model name]:model name' \\
                                        '--tts[TTS vendor]:vendor name' \\
                                        '--asr[ASR vendor]:vendor name' \\
                                        '--json[Output as JSON]' \\
                                        '--dry-run[Show request without sending]' \\
                                        '--profile[Config profile to use]:profile name'
                                    ;;
                            esac
                            ;;
                    esac
                    ;;
                auth)
                    _arguments -C \\
                        '1:subcommand:->subcmd' \\
                        '*::arg:->subargs'
                    case $state in
                        subcmd)
                            _describe -t commands 'auth subcommand' auth_commands
                            ;;
                    esac
                    ;;
                config)
                    _arguments -C \\
                        '1:subcommand:->subcmd' \\
                        '*::arg:->subargs'
                    case $state in
                        subcmd)
                            _describe -t commands 'config subcommand' config_commands
                            ;;
                    esac
                    ;;
                preset)
                    _arguments -C \\
                        '1:subcommand:->subcmd' \\
                        '*::arg:->subargs'
                    case $state in
                        subcmd)
                            _describe -t commands 'preset subcommand' preset_commands
                            ;;
                        subargs)
                            case $words[1] in
                                use)
                                    _arguments \\
                                        '1:preset name:(${PRESET_NAMES.join(' ')})'
                                    ;;
                            esac
                            ;;
                    esac
                    ;;
                completion)
                    _arguments -C \\
                        '1:subcommand:->subcmd'
                    case $state in
                        subcmd)
                            _describe -t commands 'completion subcommand' completion_commands
                            ;;
                    esac
                    ;;
            esac
            ;;
    esac
}

_convoai "$@"
`;
}

// ─── Fish Completion Script ───────────────────────────────────────────────

function generateFishScript(): string {
  const lines: string[] = [
    '# convoai fish completion',
    '# Generated by: convoai completion fish',
    '',
    '# Disable file completions by default',
    'complete -c convoai -f',
    '',
    '# Helper: no subcommand entered yet',
    "function __convoai_no_subcommand",
    "    set -l cmd (commandline -opc)",
    '    if test (count $cmd) -eq 1',
    '        return 0',
    '    end',
    '    return 1',
    'end',
    '',
    '# Helper: check if current command group matches',
    'function __convoai_using_command',
    '    set -l cmd (commandline -opc)',
    '    if test (count $cmd) -lt 2',
    '        return 1',
    '    end',
    '    if test "$cmd[2]" = "$argv[1]"',
    '        return 0',
    '    end',
    '    return 1',
    'end',
    '',
    '# Helper: check if current subcommand matches',
    'function __convoai_using_subcommand',
    '    set -l cmd (commandline -opc)',
    '    if test (count $cmd) -lt 3',
    '        return 1',
    '    end',
    '    if test "$cmd[2]" = "$argv[1]" -a "$cmd[3]" = "$argv[2]"',
    '        return 0',
    '    end',
    '    return 1',
    'end',
    '',
    '# ── Top-level commands ──────────────────────────────────────',
    'complete -c convoai -n __convoai_no_subcommand -a auth -d "Manage authentication credentials"',
    'complete -c convoai -n __convoai_no_subcommand -a agent -d "Manage ConvoAI agents"',
    'complete -c convoai -n __convoai_no_subcommand -a config -d "Manage CLI configuration"',
    'complete -c convoai -n __convoai_no_subcommand -a preset -d "Manage agent presets"',
    'complete -c convoai -n __convoai_no_subcommand -a completion -d "Generate shell completion scripts"',
    '',
    '# ── agent subcommands ──────────────────────────────────────',
    'complete -c convoai -n "__convoai_using_command agent" -a start -d "Start a new ConvoAI agent"',
    'complete -c convoai -n "__convoai_using_command agent" -a stop -d "Stop a running agent"',
    'complete -c convoai -n "__convoai_using_command agent" -a status -d "Show agent status"',
    'complete -c convoai -n "__convoai_using_command agent" -a list -d "List running agents"',
    'complete -c convoai -n "__convoai_using_command agent" -a update -d "Update a running agent"',
    'complete -c convoai -n "__convoai_using_command agent" -a speak -d "Send text for the agent to speak"',
    'complete -c convoai -n "__convoai_using_command agent" -a interrupt -d "Interrupt the agent"',
    'complete -c convoai -n "__convoai_using_command agent" -a history -d "Show conversation history"',
    'complete -c convoai -n "__convoai_using_command agent" -a turns -d "Show conversation turns"',
    'complete -c convoai -n "__convoai_using_command agent" -a watch -d "Watch agent status in real time"',
    '',
    '# ── agent start flags ──────────────────────────────────────',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l channel -s c -d "RTC channel name" -r',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l preset -d "Use a built-in preset" -r -a "' + PRESET_NAMES.join(' ') + '"',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l model -d "LLM model name" -r',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l tts -d "TTS vendor" -r',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l asr -d "ASR vendor" -r',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l json -d "Output as JSON"',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l dry-run -d "Show request without sending"',
    'complete -c convoai -n "__convoai_using_subcommand agent start" -l profile -d "Config profile to use" -r',
    '',
    '# ── auth subcommands ──────────────────────────────────────',
    'complete -c convoai -n "__convoai_using_command auth" -a login -d "Authenticate with the Agora ConvoAI platform"',
    'complete -c convoai -n "__convoai_using_command auth" -a logout -d "Remove stored credentials"',
    'complete -c convoai -n "__convoai_using_command auth" -a status -d "Show current authentication status"',
    '',
    '# ── config subcommands ─────────────────────────────────────',
    'complete -c convoai -n "__convoai_using_command config" -a init -d "Initialize configuration"',
    'complete -c convoai -n "__convoai_using_command config" -a set -d "Set a configuration value"',
    'complete -c convoai -n "__convoai_using_command config" -a get -d "Get a configuration value"',
    'complete -c convoai -n "__convoai_using_command config" -a show -d "Show full configuration"',
    'complete -c convoai -n "__convoai_using_command config" -a path -d "Show config file path"',
    '',
    '# ── preset subcommands ─────────────────────────────────────',
    'complete -c convoai -n "__convoai_using_command preset" -a list -d "List available presets"',
    'complete -c convoai -n "__convoai_using_command preset" -a use -d "Use a preset configuration"',
    '',
    '# ── preset use: complete preset names ──────────────────────',
    'complete -c convoai -n "__convoai_using_subcommand preset use" -a "' + PRESET_NAMES.join(' ') + '" -d "Preset name"',
    '',
    '# ── completion subcommands ─────────────────────────────────',
    'complete -c convoai -n "__convoai_using_command completion" -a bash -d "Generate bash completion script"',
    'complete -c convoai -n "__convoai_using_command completion" -a zsh -d "Generate zsh completion script"',
    'complete -c convoai -n "__convoai_using_command completion" -a fish -d "Generate fish completion script"',
    'complete -c convoai -n "__convoai_using_command completion" -a install -d "Auto-detect shell and install completions"',
  ];

  return lines.join('\n') + '\n';
}

// ─── Install Logic ────────────────────────────────────────────────────────

const COMPLETION_MARKER = '# convoai shell completions';

function detectShell(): 'bash' | 'zsh' | 'fish' | null {
  const shell = process.env.SHELL ?? '';
  if (shell.endsWith('/zsh')) return 'zsh';
  if (shell.endsWith('/bash')) return 'bash';
  if (shell.endsWith('/fish')) return 'fish';
  return null;
}

function installCompletions(): void {
  const shell = detectShell();

  if (!shell) {
    printError(
      `Could not detect shell from $SHELL (${process.env.SHELL ?? 'unset'}).`,
    );
    printHint('Run `convoai completion bash`, `convoai completion zsh`, or `convoai completion fish` and install manually.');
    process.exitCode = 1;
    return;
  }

  const home = homedir();

  switch (shell) {
    case 'bash': {
      const rcFile = join(home, '.bashrc');
      const snippet = `\n${COMPLETION_MARKER}\neval "$(convoai completion bash)"\n`;
      if (alreadyInstalled(rcFile)) {
        printSuccess('Bash completions are already installed in ~/.bashrc');
        return;
      }
      appendFileSync(rcFile, snippet, 'utf-8');
      printSuccess('Bash completions installed to ~/.bashrc');
      printHint('Restart your shell or run `source ~/.bashrc` to activate.');
      break;
    }
    case 'zsh': {
      const rcFile = join(home, '.zshrc');
      const snippet = `\n${COMPLETION_MARKER}\neval "$(convoai completion zsh)"\n`;
      if (alreadyInstalled(rcFile)) {
        printSuccess('Zsh completions are already installed in ~/.zshrc');
        return;
      }
      appendFileSync(rcFile, snippet, 'utf-8');
      printSuccess('Zsh completions installed to ~/.zshrc');
      printHint('Restart your shell or run `source ~/.zshrc` to activate.');
      break;
    }
    case 'fish': {
      const fishDir = join(home, '.config', 'fish', 'completions');
      const fishFile = join(fishDir, 'convoai.fish');
      mkdirSync(fishDir, { recursive: true });
      writeFileSync(fishFile, generateFishScript(), 'utf-8');
      printSuccess(`Fish completions installed to ${fishFile}`);
      printHint('Restart your shell to activate. Fish loads completions automatically.');
      break;
    }
  }
}

function alreadyInstalled(rcFile: string): boolean {
  if (!existsSync(rcFile)) return false;
  const content = readFileSync(rcFile, 'utf-8');
  return content.includes(COMPLETION_MARKER);
}

// ─── Command Registration ─────────────────────────────────────────────────

export function registerCompletion(program: Command): void {
  const completion = program
    .command('completion')
    .description('Generate shell completion scripts');

  completion
    .command('bash')
    .description('Output bash completion script')
    .action(() => {
      try {
        process.stdout.write(generateBashScript());
      } catch (error) {
        handleError(error);
      }
    });

  completion
    .command('zsh')
    .description('Output zsh completion script')
    .action(() => {
      try {
        process.stdout.write(generateZshScript());
      } catch (error) {
        handleError(error);
      }
    });

  completion
    .command('fish')
    .description('Output fish completion script')
    .action(() => {
      try {
        process.stdout.write(generateFishScript());
      } catch (error) {
        handleError(error);
      }
    });

  completion
    .command('install')
    .description('Auto-detect shell and install completions to the appropriate rc file')
    .action(() => {
      try {
        installCompletions();
      } catch (error) {
        handleError(error);
      }
    });
}
