#!/usr/bin/env tsx
import { createHash } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SALT = createHash('sha256').update('convoai-embedded-v1').digest();

function encrypt(plaintext: string): string {
  const data = Buffer.from(plaintext);
  const encrypted = Buffer.from(data.map((b, i) => b ^ SALT[i % SALT.length]));
  return encrypted.toString('hex');
}

const qwen = process.env.CONVOAI_QWEN_KEY;
const minimax = process.env.CONVOAI_MINIMAX_KEY;

const keysDir = join(__dirname, '..', 'src', 'keys');
mkdirSync(keysDir, { recursive: true });

if (!qwen || !minimax) {
  console.error('⚠ Missing CONVOAI_QWEN_KEY and/or CONVOAI_MINIMAX_KEY');
  console.error('  Writing empty embedded.ts (built-in keys will not work)');
  writeFileSync(
    join(keysDir, 'embedded.ts'),
    '// No keys embedded (missing env vars)\nexport const EMBEDDED_KEYS: Record<string, string> = {};\n',
  );
  process.exit(0);
}

const keys: Record<string, string> = {
  qwen: encrypt(qwen),
  minimax: encrypt(minimax),
};

const content = `// Auto-generated by scripts/embed-keys.ts — do not edit or commit
export const EMBEDDED_KEYS: Record<string, string> = ${JSON.stringify(keys, null, 2)};
`;

writeFileSync(join(keysDir, 'embedded.ts'), content);
console.log('✓ Embedded keys written to src/keys/embedded.ts');
